### ISSUE TITLE
Alter - define data type

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#100]
The [`alter` method](https://handsontable.com/docs/7.4.2/Core.html#alter) is supposed to change the number of rows and columns in the table. However, these options is only available for array type data. I have to add that this is a frequently asked question - why it doesn't work when I have an object.

Since we do not have any plans on allowing `alter` to manipulate objects we should define that this option is dedicated to arrays.

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7275
