### ISSUE TITLE
Clearly inform about the need for colHeaders if you want to use indicators. 

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#102]
When we use both plugins - `nestedHeaders` and `hiddenColumns` with `indicators` option - but without a `colHeaders` setting option indicator don't appear. `nestedHeaders` alone isn't sufficient to show indicator.

So `colHeaders` is crucial to `hiddenColumns` plugin (with `indicators` set to true) in the headers work properly.

I think the best place to do it is in the demo section: https://handsontable.com/docs/7.4.2/demo-hiding-columns.html#examples

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/docs/pull/154
