### ISSUE TITLE
nestedRows option has the wrong link

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#104]
In https://handsontable.com/docs/7.4.2/Options.html#nestedRows on `quick setup of the Nested rows` direct to the wrong site -> https://docs.handsontable.kbudnik/pro/next/demo-nested-rows.html

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7196

**Comment by scarletfog** [comment]
Closing it as won't do, it's working fine with 8.0.0, more discussion details here: https://github.com/handsontable/handsontable/pull/7196
