### ISSUE TITLE
Mismatch in an undo/redo

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#107]
There is a complete misunderstanding if it comes to undo/redo on our docs.

In members Options, we have only `undo` which has to be a `boolean` and if `true`, undo/redo functionality is enabled - https://handsontable.com/docs/7.4.2/Options.html#undo. 

But when we set `undo` with `false` and try to use `Undo` by `contextMenu` we got an error `undo.js:12 Uncaught TypeError: this.undo is not a function`. If we use a keyboard shortcut for undo `Ctrl + Z` and redo `Ctrl + Y` we don't have this error and functionality is turned off.
Furthermore, after some changes in `contextMenu` has both options (`Undo` and `Redo`) are active at the same time. It should be only active `Undo` before use it.

If we set to `true` it works just like without `undo` option, because `undoRedo` is enabled by default. So setting `undo` to `true` it seems meaningless. However, not altogether because `undo` (`redo`) is important to `isUndoAvailable` (respectively `isRedoAvailable`).

On the other hand, we missed the rest of the options from undo/redo functionality. Including ` redo`, `clearUndo`, `isUndoAvailable`, `isRedoAvailable` and `undoRedo` itself.

**Comment by swistach** [comment]
It is done.
ContextMenu's items works on common interface `this.getPlugin('undoRedo')` instead of `this.undo`.
API reference for the UndoRedo plugin has all public methods.
