### ISSUE TITLE
JSFiddle POST button has hack inside of the CSS panel

### ISSUE THREAD

**Issue by oskarkrawczyk** [handsontable/docs#111]
Specifically referring to this:

```
</style><!-- Ugly Hack due to jsFiddle issue -->

<script src="https://cdn.jsdelivr.net/npm/handsontable@7.4.2/dist/handsontable.full.min.js"></script>
<link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/handsontable@7.4.2/dist/handsontable.full.min.css">
```

Can someone from the team elaborate why is this there, and what issues is this addressing?

I see no issues whatsoever when moving the JS and CSS into the resources panel.

**Comment by AMBudnik** [comment]
It's it our demos for ages so it might be already fixed.  
Surely we enjoy using CSS part to share scripts as it is easier for us to test (you can see the version) but when it comes to the 

> ```
> Ugly Hack due to jsFiddle issue
> ```

@jansiegel do you remember what it was all about? I guess it say it before I joined Handsontable a few years ago.

**Comment by jansiegel** [comment]
I don't really remember... I _think_ it was added because the JSFiddle resources were loaded too late (after the code from the JS section), but I'm not 100% sure. Maybe @warpech remembers?

**Comment by oskarkrawczyk** [comment]
I do vaguely recall our docs mentioning some kind of a CSS hack many many years and fixes ago, but from what I see the examples render fine when loading external stuff via the Resources panel.

If someone ends up refreshing docs on your end, it would be really cool to switch away from the hack. No rush though.

Btw. @AMBudnik thanks for being so vigilant when it comes to JSFiddle misbehaviors, it's almost like I don't need to write tests :P

**Comment by AMBudnik** [comment]
@oskarkrawczyk  a week without a new JSFiddle demo is a wasted week so you can count on me :muscle:

**Comment by warpech** [comment]
> I don't really remember... I think it was added because the JSFiddle resources were loaded too late (after the code from the JS section), but I'm not 100% sure. Maybe @warpech remembers?

I remember that the problem was to set JS resources in a fiddle dynamically created using JSFiddle's REST API (`POST` request). I am not sure if that was buggy or unsupported.

**Comment by swistach** [comment]
We have changed this. In the new documentation, we use external scripts and links to the HTML section.
