### ISSUE TITLE
Change row to column in HiddenColumns section

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#112]
Change all occurring of rows to columns in the comment section in HiddenColumns - https://handsontable.com/docs/7.4.2/HiddenColumns.html

Instead of `show single row` and `hide single row` should be `show single column` and `hide single column`.

The issue has been since version 5.0.0.

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7195
