### ISSUE TITLE
Filter from the outside the table loads older version of Handsontable than chosen

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#113]
Filter from the outside the table loads older version of Handsontable than chosen. I'm on Handsontable v7.4.2 but when I click edit

![Zrzut ekranu 2020-05-13 o 15 25 32](https://user-images.githubusercontent.com/10757813/81818259-1b766680-952e-11ea-8385-11261dfaafc0.png)

version loaded is pro/1.12.0
src: https://handsontable.com/docs/7.4.2/demo-filtering.html

**Comment by aninde** [comment]
Demo still leads to pro/1.12.0v with latests version of v8.3.0
I've moved this issue to the `In development` pipeline because it's not done yet.

**Comment by AMBudnik** [comment]
This issue is no longer replicable. The demo loads version @latest
