### ISSUE TITLE
Repetition in the text - Autofill.fill source is defined two times.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#114]
`Autofill.fill` source is defined two times.

![Zrzut ekranu 2020-05-25 o 09 11 25](https://user-images.githubusercontent.com/10757813/82787939-c7417f80-9e67-11ea-9ca5-d5f17ca7ffc9.png)

src: https://handsontable.com/docs/7.4.2/tutorial-using-callbacks.html

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/docs/pull/139
