### ISSUE TITLE
Version dropdown generates 404 links

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/docs#115]
@wojciechczerniak commented on [Tue Dec 04 2018](https://github.com/handsontable/handsontable.com-v2/issues/32)

Our dropdown menu with links to the older version of current documentation page creates 404 links to the pages that didn't exist at the time the particular documentation version was published.

![image](https://user-images.githubusercontent.com/4718998/49449246-c4b61a80-f7da-11e8-88f0-67c4c14dbcf4.png)

Few examples of non existent links:
https://handsontable.com/docs/1.18.1/frameworks-wrapper-for-vue-custom-renderer-example.html
https://handsontable.com/docs/1.15.1/frameworks-wrapper-for-vue-custom-renderer-example.html
https://handsontable.com/docs/1.14.3/frameworks-wrapper-for-vue-hot-reference.html
https://handsontable.com/docs/1.14.2/frameworks-wrapper-for-vue-vuex-example.html
https://handsontable.com/docs/1.14.3/MultiColumnSorting.html
https://handsontable.com/docs/1.18.1/MultiColumnSorting.html
https://handsontable.com/docs/1.14.0/MultiColumnSorting.html

At this moment I have no idea how we can solve this. We can't put `rel="nofollow"` on javascript links and `robots.txt` is hard to update whenever we publish new docs version. Ideas are welcome.

---

@krzysztofspilka commented on [Fri May 29 2020](https://github.com/handsontable/handsontable.com-v2/issues/32#issuecomment-635860813)

@wojciechczerniak shouldn't we move this task to the `docs` repo?

**Comment by swistach** [comment]
@wojciechczerniak, do we want to fix redirects to missing URLs for the old documentation?

**Comment by wojciechczerniak** [comment]
No

**Comment by swistach** [comment]
So I close this issue then. Thanks!
