### ISSUE TITLE
Code sample on setBorders with getSelectedRange method return an error in the console

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#119]
### Description
Using the below code sample

![Zrzut ekranu 2020-07-1 o 08 56 18](https://user-images.githubusercontent.com/10757813/86212663-c1327300-bb78-11ea-9ed7-b7595f159ea7.png)

produces an uncaught error
![Zrzut ekranu 2020-07-1 o 08 56 56](https://user-images.githubusercontent.com/10757813/86212720-de674180-bb78-11ea-840f-228106473211.png)
src https://handsontable.com/docs/7.4.2/CustomBorders.html#setBorders

### Details
Code breaks when the following line of code is called 

> customBordersPlugin.setBorders(hot.getSelectedRange(), {left: {hide: false, width: 2, color: 'blue'}});

the first part is executed successfully.

The second part is based on `getSelectedRange` which returns an object while the first parameter of `setBorders` method has to be an array.

### Demo 
* 7.4.2 https://jsfiddle.net/zoh1txeq/ (broken)

**Comment by AMBudnik** [comment]
We need to add the `selectCell()` method to get this example working https://jsfiddle.net/zoh1txeq/3/

![Zrzut ekranu 2020-07-1 o 09 14 15](https://user-images.githubusercontent.com/10757813/86214289-428b0500-bb7b-11ea-89b1-202105524b2f.png)

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7194
