### ISSUE TITLE
This method does **not** need to return any value

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#121]
In https://handsontable.com/docs/7.4.2/tutorial-cell-editor.html `open`, `close` and `focus` method we write that `This method does need to return any value.`.

It should be `This method does **not** need to return any value.`.

`Inform` - https://github.com/handsontable/handsontable/issues/7141

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/docs/pull/138
