### ISSUE TITLE
Fix the installation example for Vue

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#130]
As @pnowak discovered

If we initialize the Vue app like in this example - https://handsontable.com/docs/8.0.0/frameworks-wrapper-for-vue-simple-example.html - we got an error `[Vue warn]: Cannot find element: example1`.

**Comment by scarletfog** [comment]
Probably it is worth adding an additional step/note also to React and/or Angular to keep the guides consistent.

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/docs/pull/137

Angular example should be discussed someday. It is more complex yet it should not confuse the users.
