### ISSUE TITLE
Unwanted line break in the method description

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/docs#134]
@scarletfog I noticed that descriptions in the API reference contain unnecessary line breaks in random places: https://handsontable.com/docs/8.0.0/Options.html#rowHeights

`Defines row heights in pixels. Accepts numbers, strings (that will be converted into a number), array of numbers`
`[-------- line break -------]`
`(if you want to define row height separately for each row) or a function (if you want to set row height dynamically
`

I spotted this issue in some other places too, like so:

https://handsontable.com/docs/8.0.0/Options.html#sortByRelevance
https://handsontable.com/docs/8.0.0/Options.html#tabMoves
https://handsontable.com/docs/8.0.0/Options.html#trimDropdown

**Comment by scarletfog** [comment]
@krzysztofspilka this is a clone of https://github.com/handsontable/docs/issues/35

And these descriptions are generated from JSDoc comments in the code. I need a dev to discuss how it is interpreted and which rules force to produce a `<br>` (sometimes an extra line in the comment causes it, sometimes..not?). @budnix ?

**Comment by budnix** [comment]
@scarletfog True. The issue has to be investigated within the docs repository. This can be a difficult issue to solve as some of the API descriptions are more complicated than a simple one-liner text (examples, custom formatting, etc.).

**Comment by swistach** [comment]
We have changed this in our new documentation.
