### ISSUE TITLE
Add docs for isCommand option from Context Menu

### ISSUE THREAD

**Issue by cgatesman** [handsontable/docs#14]
Disclaimer: Currently running 0.29.1

### What I'm trying to do

I want context menu items that are an `<a href="..." target="_blank">` (This is supported with jQuery contextMenu using isHtmlName.) rather than dynamic JavaScript looking like a popup to open a page in another browser tab.  

![screen shot 2017-05-05 at 3 51 34 pm](https://cloud.githubusercontent.com/assets/6276072/25762799/38e7902c-31ae-11e7-826e-980ca84e7185.png)

The link location is dynamic based cell data in the current row selected, so it does need to be dynamically generated.

### My problem

jQuery contextMenu supports having HTML items; however, I need the `href` dynamically set.  I can think of two ways to do this:

1. Adjust the contextMenu items before building the contextMenu.
    - Unfortunately, there is no `beforeContextMenuShow` to do this (**Feature Request?**)
    - I tried to set the contextMenu `events.show` (http://swisnl.github.io/jQuery-contextMenu/docs.html#events), but it doesn't appear to get called.  Is Handsontable stripping this or just not allowing it?
2. Change `a[href]` attributes in the DOM after the contextMenu is completely built and shown.  This works; however, **it looks like Handsontable is capturing and not propagating the click on the menu item `a[href]`.**

This appears to be the same problem in jQuery contextMenu: https://github.com/swisnl/jQuery-contextMenu/issues/517

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/handsontable/pull/7208
