### ISSUE TITLE
[React] Add hotColumn component demo for object data

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#142]
### Description

All the examples for the `hotColumn` component are made for array data. To make them work for objects we need to add some extra logic so it would be great to have an object demo as well.

Here's an object demo for the **Declaring a custom renderer as a component** paragraph 
https://codesandbox.io/s/declaring-a-custom-renderer-as-a-component-forked-3jnmn
to show the difference in building a working example.

What we needed to alter
* add `columns` declaration with `data` reference.
* add `data` option to the HotColumn element.

### Links

1. Object demo https://codesandbox.io/s/declaring-a-custom-renderer-as-a-component-forked-3jnmn
2. Docs for hotColumn component https://handsontable.com/docs/8.0.0/frameworks-wrapper-for-react-hot-column.html

**Comment by scarletfog** [comment]
@AMBudnik as discussed today - we don't need to do both: columns.. + data prop. Here is my suggestion:
https://codesandbox.io/s/hotcolumn-an-and-array-of-objects-b9799?file=/src/index.js

I can prepare an alternative example with `columns: [{ data: "id" }, { data: "name" }]` if needed. You know best where clients got lost.

I will also mention that `HotColumn` is like `columns` https://handsontable.com/docs/8.0.0/tutorial-data-sources.html?_ga=2.132796301.2005244191.1598520771-1714913993.1593077094#page-data-schema + `HotTable` and `hot` are alike too

**Comment by AMBudnik** [comment]
> @AMBudnik as discussed today - we don't need to do both: columns.. + data prop

Cool! Thanks for checking @scarletfog I would go with the `hotColumn` data declaration.

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/docs/pull/144
