### ISSUE TITLE
Typo: A typo in some of the Plugin doc example snippets.

### ISSUE THREAD

**Issue by saisandeepvaddi** [handsontable/docs#155]
### Description

I guess it's a possible typo. `data` field written as `date` in some examples. And, I didn't find any `date` field in `options`.

### Links

https://handsontable.com/docs/8.0.0/HiddenRows.html
https://handsontable.com/docs/8.0.0/BindRowsWithHeaders.html
https://handsontable.com/docs/8.0.0/NestedHeaders.html

### Example of one page:

![Screenshot 2020-09-16 192925](https://user-images.githubusercontent.com/13838175/93413619-a6b19100-f86d-11ea-867f-a69a57e9f755.jpg)

Please note that I did not go through each page. So there may be more places.

**Comment by AMBudnik** [comment]
You're right. Thank you for sharing @saisandeepvaddi 

@scarletfog we need a quick fix here.

**Comment by scarletfog** [comment]
@AMBudnik I am on it 💪

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7278 
The change will be visible in the next release 🚂
