### ISSUE TITLE
beforeAutofill - missing return information.

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#156]
### Description
Since 8.0.0 we can stop the execution of this hook by returning `false`. 
Here is a link to PR - https://github.com/handsontable/handsontable/pull/5791.
And here is a demo - https://jsfiddle.net/o6a1x8fn/

### Links
https://handsontable.com/docs/8.0.0/Hooks.html#event:beforeAutofill

**Comment by scarletfog** [comment]
@pnowak do you mean adding something like this?
Returns: {void|boolean} The execution of this hook can be stopped by returning `false`
?

**Comment by AMBudnik** [comment]
For `beforePaste` we have a demo with `return false` https://handsontable.com/docs/8.0.0/Hooks.html#event:beforePaste

and this message

![Zrzut ekranu 2020-09-17 o 13 18 58](https://user-images.githubusercontent.com/10757813/93463669-5deaee00-f8e8-11ea-9dc4-7e96f1a68175.png)

reference https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/pluginHooks.js#L1201

**Comment by scarletfog** [comment]
Nice! Thanks @AMBudnik ❤️

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7333
