### ISSUE TITLE
404 for Comments tutorial

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#159]
### Description

When we click on **our Comments documentation** on the following page https://handsontable.com/docs/8.0.0/demo-comments_.html

![image](https://user-images.githubusercontent.com/10757813/93755594-dcef6780-fc03-11ea-8657-ff433c17b4f8.png)

We are redirected to https://handsontable.com/docs/8.0.0/Comments.html which doesn't exist.

**Comment by scarletfog** [comment]
I checked and apparently I added a tag to the class so it should fix the problem. Please do not close the issue yet, I will do some testing before the release.

**Comment by aninde** [comment]
This link will be fixed by `v8.1.0`. 
Closing #159 as done.
