### ISSUE TITLE
beforeCreateRow - missing return information.

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#160]
### Description
We can stop the execution of this hook by returning false. 
So we have to write for example - `Returns: {*|boolean} If false then creating rows is cancelled.`

Here is a demo - https://jsfiddle.net/fwdpogv5/

### Links
https://handsontable.com/docs/8.0.0/Hooks.html#event:beforeCreateRow

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7333
