### ISSUE TITLE
404 for DropdownMenu

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#161]
### Description
If you click on **DropdownMenu** in `beforeDropdownMenuSetItems` or `beforeDropdownMenuShow ` hooks section you got a 404.
The source of this bug is that `dropdownMenu` plugin disappears from our plugins list.

### Links
https://handsontable.com/docs/8.0.0/DropdownMenu.html

### Steps to reproduce

1. Click on **DropdownMenu** in https://handsontable.com/docs/8.0.0/Hooks.html#event:beforeDropdownMenuSetItems or in https://handsontable.com/docs/8.0.0/Hooks.html#event:beforeDropdownMenuShow

### Your environment

* Handsontable version: 8.0.0.
* Browser Name and version:
* Operating System:

**Comment by scarletfog** [comment]
@pnowak this is probably related to disabling eslint rule (same as in https://github.com/handsontable/docs/issues/159). JSDoc cannot properly render the descriptions.

I am in the middle of testing the changes I made https://github.com/handsontable/handsontable/pull/7242/files so far so good.

**Comment by scarletfog** [comment]
@aninde could you please test if it works with 8.1.0? If so, we can close the issue.

**Comment by aninde** [comment]
These links are fixed in `v8.1.0` of docs.

All links leading to `DropdownMenu` works well with `v8.1.0`.
- `afterDropdownMenuDefaultOptions`
- `afterDropdownMenuHide`
- `afterDropdownMenuShow`
- `beforeDropdownMenuSetItems`
- `beforeDropdownMenuShow`

Closing as  #161 done.
