### ISSUE TITLE
404 for Comments

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#164]
### Description

If you click on first **Comments** in https://handsontable.com/docs/8.0.0/Options.html#comments you got a 404.

### Links

https://handsontable.com/docs/8.0.0/Options.html#comments

### Steps to reproduce

1. Click on **Comments** in https://handsontable.com/docs/8.0.0/Options.html#comments

### Your environment

* Handsontable version: 8.0.0.
* Browser Name and version:
* Operating System:

**Comment by scarletfog** [comment]
@aninde could you please test if it works with 8.1.0? If so, we can close the issue.

**Comment by aninde** [comment]
It looks like this link has been fixed in `v8.1.0` of documentation.


<img width="621" alt="Screenshot 2020-10-01 at 08 31 48" src="https://user-images.githubusercontent.com/30186818/94775740-b62def80-03c0-11eb-91df-19e1bccaf928.png">
