### ISSUE TITLE
beforeRemoveCellMeta - missing return information.

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#165]
### Description

We can stop the execution of this hook by returning false.
So we have to write for example - Returns: {*|boolean} If false then cell meta isn't removed.

Here is a demo - https://jsfiddle.net/csjozt94/

### Links

https://handsontable.com/docs/8.0.0/Hooks.html#event:beforeRemoveCellMeta

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7333
