### ISSUE TITLE
beforeRemoveCol - missing return information.

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#167]
### Description

We can stop the execution of this hook by returning false.
So we have to write for example - Returns: {*|boolean} If false then Remove Column is cancelled.

Here is a demo - https://jsfiddle.net/0w5hzpL6/

### Links

https://handsontable.com/docs/8.0.0/Hooks.html#event:beforeRemoveCol

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7333
