### ISSUE TITLE
Dropdown menu filter - show only checkbox list

### ISSUE THREAD

**Issue by lance-p** [handsontable/docs#17]
I've found this example in the documentation which shows a custom drop down menu with only the filter by value condition: https://docs.handsontable.com/pro/1.2.0/demo-filtering.html#dropdown

The dropdown menu items are set explicitly by passing values to the dropdownMenu array:

`dropdownMenu:` ['filter_by_condition', 'filter_action_bar']`

But I only want to show the "checkbox list" (under select all) in the dropdown menu as in this example: 
https://handsontable.com/examples.html?_ga=2.38233699.1704423548.1502423159-1885395872.1502423159&headers&filters

Is there a value I can pass to the drodownMenu array (or some other means) to do this?

**Comment by AMBudnik** [comment]
The issue continued here https://github.com/handsontable/docs/issues/52 (relates to the dropdiwn menu as well)
