### ISSUE TITLE
Data Validation Demo does not work in Fiddle

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#17]
Demo: http://docs.handsontable.com/0.17.0/demo-data-validation.html

While doing double <kbd>LMB</kbd> then <kbd>Enter</kbd> we get (as expected)

![zrzut ekranu 2015-09-07 o 19 35 59](https://cloud.githubusercontent.com/assets/10757813/9721265/eb048340-5597-11e5-8693-083327dfe04b.png)

When we do the same in Fiddle we get

![zrzut ekranu 2015-09-07 o 19 38 23](https://cloud.githubusercontent.com/assets/10757813/9721275/19cba99c-5598-11e5-9d3c-9d7af1084e44.png)

**Comment by budnix** [comment]
Fixed in documentation for Handsontable 0.18.0 and greater.
