### ISSUE TITLE
beforeUndo - missing return information

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#171]
### Description

We can stop the execution of this hook by returning false.
So we have to write for example - Returns: {*|boolean} If false then Undo action is cancelled.

Here is a demo - https://jsfiddle.net/7gktLp8d/

### Links

https://handsontable.com/docs/8.0.0/Hooks.html#event:beforeUndo

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7333
