### ISSUE TITLE
Missing information about new feature in the Handsontable-Vue

### ISSUE THREAD

**Issue by aninde** [handsontable/docs#172]
### Description
The upcoming version of Handsontable-Vue includes a new feature: The possibility to differentiate editor settings for each column by handing over a key. So far the editor instance was one for the whole HOT.

PR of this feature 
https://github.com/handsontable/vue-handsontable-official/pull/178

A second pull will be created for additional tests.

> Slack discussions about additional tests https://handsoncode.slack.com/archives/GR8S89QD7/p1602140252000100

**Comment by scarletfog** [comment]
I will add the information somewhere here: https://handsontable.com/docs/8.1.0/frameworks-wrapper-for-vue-custom-editor-example.html

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/docs/pull/207
