### ISSUE TITLE
Options>data - remove function as a possible option

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#173]
### Description
URL: https://handsontable.com/docs/8.1.0/Options.html#data
Reference: https://github.com/handsontable/support/issues/254

Task: Remove "or a function" as the data cannot be a function.
That has been checked and confirmed with @warpech along with the fact, that we throw the following error

![Zrzut ekranu 2020-10-9 o 11 41 38](https://user-images.githubusercontent.com/10757813/95568374-6edcda00-0a24-11eb-8689-c49169ba1e5f.png)

**Comment by warpech** [comment]
Note that function is an invalid type on the top level of the configuration object, but a valid type at the `columns` level (see https://github.com/handsontable/support/issues/254#issuecomment-706106571). It has to be clear from the docs.

**Comment by AMBudnik** [comment]
That's true.
@warpech also created a demo that we can consider while rebuilding the data section https://jsfiddle.net/warpech/rujqx2pc/4/

**Comment by warpech** [comment]
> @warpech also created a demo that we can consider while rebuilding the data section https://jsfiddle.net/warpech/rujqx2pc/4/

To clarify, I only wrote the part in `beforeChange` to answer the customer's question:

> How do I know which cell was changed in beforeChanged event when column is not a property but is a function?

The remaining part of the fiddle is the property of our customer
