### ISSUE TITLE
setDataAtCell - define that if source is not provided it is described as 'edit'

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#179]
![Zrzut ekranu 2020-10-9 o 14 10 36](https://user-images.githubusercontent.com/10757813/95581381-38f62080-0a39-11eb-8509-49f14ef02ca3.png)

### Description
We do not mention that if `source` [optional] is not provided then the source is described as 'edit'.

In this demo we use `setDataAtCell(0, 0, 'test')`https://jsfiddle.net/AMBudnik/1b0md8yk/ and the result of the 

```js
beforeChange: (changes, source) => {
    console.log(source);
}
```

is `edit`.

### Links
* setDataAtCell - https://handsontable.com/docs/8.1.0/Core.html#setDataAtCell

**Comment by scarletfog** [comment]
`emptySelectedCells` will probably act the same way, it calls `setDataAtCell`. Could you please double-check? I will make the changes.

**Comment by AMBudnik** [comment]
@scarletfog you're right. The `emptySelectedCells` also is described as 'edit' change. 

Demo https://jsfiddle.net/AMBudnik/098nw1am/
