### ISSUE TITLE
setDataAtCell - update hooks' names and provide links

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#180]
![Zrzut ekranu 2020-10-9 o 14 10 36](https://user-images.githubusercontent.com/10757813/95581820-f08b3280-0a39-11eb-85ed-e9de4fae4db4.png)

### Description
Our hooks changed the names

* `onAfterChange` is now `afterChange`
* `onBeforeChange` is not `beforeChange`

We should change that info in the `source` description and add the links to those hooks.

### Links
* setDataAtCell - https://handsontable.com/docs/Core.html#setDataAtCell
* afterChange - https://handsontable.com/docs/Hooks.html#event:afterChange
* beforeChange - https://handsontable.com/docs/Hooks.html#event:beforeChange

**Comment by scarletfog** [comment]
Partially done in https://github.com/handsontable/handsontable/pull/7345 (I missed the links :/)

**Comment by aninde** [comment]
As this was done partially I moved it to the `In development` to be finished.

**Comment by AMBudnik** [comment]
This issue is no longer replicable using the new documentation.
