### ISSUE TITLE
Define 'Utilities'

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#186]
### Description

I'm wondering if we can name `dropdownMenu` a utility? 
Maybe if we could define that term we could add something more in that section.

### Links
https://handsontable.com/docs/8.1.0/demo-context-menu.html (first utility, 'Utilities' themselves are not a linked page)

**Comment by swistach** [comment]
In the new documentation, we named this section as "Column menu": https://handsontable.com/docs/column-menu/
