### ISSUE TITLE
checkTemplate - wrong default set up

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#188]
### Description
The default value of the `checkTemplate` option is said to be `true`, 

![Zrzut ekranu 2020-10-12 o 12 36 47](https://user-images.githubusercontent.com/10757813/95737256-ac8d6d00-0c87-11eb-8d46-38cd056de4f2.png)

but it is set by default to `undefined`. To check got to the console in the demo and check the result for `getSettings()` call.

Demo https://jsfiddle.net/AMBudnik/42qotga3/

Result
![Zrzut ekranu 2020-10-12 o 12 38 12](https://user-images.githubusercontent.com/10757813/95737406-e3fc1980-0c87-11eb-81b9-458187e1b09f.png)

### Links
* checkedTemplate - https://handsontable.com/docs/8.1.0/Options.html#checkedTemplate

**Comment by scarletfog** [comment]
Added here: https://github.com/handsontable/handsontable/pull/7340

**Comment by scarletfog** [comment]
This is a wontfix but the need was moved here: https://github.com/handsontable/docs/issues/215
