### ISSUE TITLE
Column sort indicator does not update for setSortConfig server-side sorting 

### ISSUE THREAD

**Issue by s1monj** [handsontable/docs#19]
### Description
Following this example:
https://handsontable.com/docs/6.2.1/ColumnSorting.html#setSortConfig

If indicator is set to true and server-side sorting is used in beforeColumnSort with setSortConfig and return false, the indicator should update accordingly.

### Steps to reproduce
1. https://handsontable.com/docs/6.2.1/ColumnSorting.html#setSortConfig

### Demo
https://jsfiddle.net/w5qymdbc/

### Your environment
* Handsontable version: 6.2.1
* Browser Name and version: Chrome 71
* Operating System: Linux

**Comment by AMBudnik** [comment]
Hey @s1monj 

I'm pleased to inform that we've solved the issue. The fixed version is `7.0.0`. 

Again, thank you for the feedback!
