### ISSUE TITLE
enterMoves - change parameter order in default value

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#191]
### Description
Here's how we define the default value for the `enterMoves`

![Zrzut ekranu 2020-10-12 o 13 00 05](https://user-images.githubusercontent.com/10757813/95739374-08a5c080-0c8b-11eb-96c8-65c4a4a2dffb.png)

but generally, the console would switch those parameters

Go to this demo https://jsfiddle.net/AMBudnik/42qotga3/ and check the console for the `enterMoves` log.

Result
![Zrzut ekranu 2020-10-12 o 13 02 57](https://user-images.githubusercontent.com/10757813/95739529-43a7f400-0c8b-11eb-876c-93ebcb6295a6.png)

### Links
enterMoves docs - https://handsontable.com/docs/8.1.0/Options.html#enterMoves

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/handsontable/pull/7341
