### ISSUE TITLE
fillHandle - wrong default set up

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#192]
### Description
We define the default value for the `fillHandle` to be true. But in the console for the `getSettings()` we can see that the default value is

![Zrzut ekranu 2020-10-12 o 13 06 37](https://user-images.githubusercontent.com/10757813/95739870-c8930d80-0c8b-11eb-8719-300a17041b32.png)

Demo for the console of the `getSettings()` method https://jsfiddle.net/AMBudnik/42qotga3/

### Links
fillHandle docs - https://handsontable.com/docs/8.1.0/Options.html#fillHandle

**Comment by scarletfog** [comment]
Added here: https://github.com/handsontable/docs/issues/192

**Comment by scarletfog** [comment]
Oh, wait a minute, so `hot.getSettings().fillHandle` will be truthy, right?

**Comment by AMBudnik** [comment]
> `{autoInsertRow: false}` or leave it as `true`

good question. I would say that `{autoInsertRow: false}`. Why?

* we share some examples where 

```js
// enable plugin in all directions and with autoInsertRow as true
fillHandle: true,

fillHandle: {
  // enable plugin in both directions and with autoInsertRow as false
  autoInsertRow: false,
},
```

and by default, we cannot add new rows while doing the fill handle.

**Comment by scarletfog** [comment]
Let's check with a 🧙‍♂️ ! @wojciechczerniak could you please have a look here? We are not 101% sure what should be communicated to the developer.

**Comment by scarletfog** [comment]
This is a wontfix but the need was moved here: https://github.com/handsontable/docs/issues/215
