### ISSUE TITLE
persistentState - wrong default set up

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#194]
### Description
We define that the default value of the `persistentState` option is

![Zrzut ekranu 2020-10-12 o 14 39 27](https://user-images.githubusercontent.com/10757813/95747436-bec3d700-0c98-11eb-8891-0d087a319d7a.png)

But the `getSettings()` tells us that it is 

![Zrzut ekranu 2020-10-12 o 14 40 15](https://user-images.githubusercontent.com/10757813/95747496-db600f00-0c98-11eb-9c8c-63195169fbbb.png)

Demo https://jsfiddle.net/AMBudnik/2yt6nzxd/

### Links
persistentState docs - https://handsontable.com/docs/8.1.0/Options.html#persistentState

**Comment by scarletfog** [comment]
Added in https://github.com/handsontable/handsontable/pull/7340 alongside the others.

**Comment by scarletfog** [comment]
This is a wontfix but the need was moved here: https://github.com/handsontable/docs/issues/215
