### ISSUE TITLE
uncheckedTemplate - wrong return set up

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#196]
### Description
The returned value in docs is `false`while the `getSettings()` method returns `undefined`.

Go to demo console to check the result https://jsfiddle.net/AMBudnik/2yt6nzxd/

### Links
uncheckedTemplate docs - https://handsontable.com/docs/8.1.0/Options.html#uncheckedTemplate

**Comment by scarletfog** [comment]
Hm... seems like for `checkedTemplate` it's the same story?

**Comment by scarletfog** [comment]
This is a wontfix but the need was moved here: https://github.com/handsontable/docs/issues/215
