### ISSUE TITLE
Data source - improve the paragraph naming

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#197]
### Description
We both agreed with @pnowak that the paragraph called **Array data source with hidden columns** should be renamed to something that does not indicate that the `hiddenColumns` are used.

### Links
Array data source with hidden columns - https://handsontable.com/docs/8.1.0/tutorial-data-sources.html#page-array-hidden
support task (origin) - https://github.com/handsontable/support/issues/258

**Comment by AMBudnik** [comment]
Having the data named `hiddenData` also appears to be unnecessary.

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/docs/pull/213
