### ISSUE TITLE
Data source - correct the typo

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#198]
### Description
There's a typo in the **Object data source with column as a function** paragraph.

> That could be a good choice, **when do you want bind** data more dynamically.

We should use **when you want bind** or **when you do want bind**

### Links
data source docs - https://handsontable.com/docs/8.1.0/tutorial-data-sources.html#page-column-func
support task (origin) - https://github.com/handsontable/support/issues/258

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/docs/pull/212
