### ISSUE TITLE
Scrolling rows and columns: demo issue

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#2]
demo: http://docs.handsontable.com/demo-scrollbars.html

Clicking <kbd>maximize table</kbd> from this:

![zrzut ekranu 2015-05-05 o 11 19 28](https://cloud.githubusercontent.com/assets/10757813/7469938/206847ce-f319-11e4-97a9-b9092fe31e3e.png)
 does this:

![zrzut ekranu 2015-05-05 o 11 19 32](https://cloud.githubusercontent.com/assets/10757813/7469942/246a6d0c-f319-11e4-8b31-7646c35b4329.png)

still occurs after scrolling the table.

**Comment by budnix** [comment]
We decided to remove this button.
