### ISSUE TITLE
The cascading configuration model - broken link

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#200]
### Description
There's a broken link in **The cascading configuration model** paragraph under

> See it yourself: http://jsperf.com/extending-settings

### Links
The cascading configuration model - https://handsontable.com/docs/8.1.0/tutorial-setting-options.html#page-cascading
support task (origin) - https://github.com/handsontable/support/issues/258

**Comment by aninde** [comment]
There are two unnecessary dots https://handsontable.com/docs/8.3.1/Options.html# in two first headers
Constructor options.
Cascading configuration.

**Comment by AMBudnik** [comment]
The mentioned link is removed in the new documentation https://handsontable.com/docs/setting-options/#overview also, the dots are not present.
