### ISSUE TITLE
List of callback that operates on source parameter - update the list

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#209]
### Description
On the Callbacks tutorial page, we have the following list

> List of callback that operates on source parameter:
> 
> * afterChange
> * afterCreateCol
> * afterCreateRow
> * afterSetDataAtCell
> * afterSetDataAtRowProp
> * afterValidate
> * beforeChange
> * beforeChangeRender
> * beforeCreateCol
> * beforeCreateRow
> * beforeValidate

However, the list is not complete. As we use the term 'List of callbacks', and not 'List of some of the callbacks' I assume that we should list all of them.

At the same time I confirm that all the hooks that are currently listed are still valid (sharing the `source`).

#### Missing hooks

* afterRemoveCol - https://handsontable.com/docs/8.1.0/Hooks.html#event:afterRemoveCol
* afterRemoveRow - https://handsontable.com/docs/8.1.0/Hooks.html#event:afterRemoveRow
* afterSetSourceDataAtCell - https://handsontable.com/docs/8.1.0/Hooks.html#event:afterSetSourceDataAtCell
* beforeRemoveCol - https://handsontable.com/docs/8.1.0/Hooks.html#event:beforeRemoveCol
* beforeRemoveRow - https://handsontable.com/docs/8.1.0/Hooks.html#event:beforeRemoveRow

### Links
* List of callback that operates on `source` parameter - https://handsontable.com/docs/8.1.0/tutorial-using-callbacks.html#page-source-definition

**Comment by swistach** [comment]
It's done.
