### ISSUE TITLE
 TypeError: Handsontable.dom.enableImmediatePropagation is not a function

### ISSUE THREAD

**Issue by KshitizGIT** [handsontable/docs#21]
I was following the documentation in https://docs.handsontable.com/0.34.5/tutorial-cell-editor.html. And on the implementing the select editor, I am getting the below error. 

Uncaught TypeError: Handsontable.dom.enableImmediatePropagation is not a function

Am I missing something ?

**Comment by AMBudnik** [comment]
Done with https://github.com/handsontable/handsontable/issues/5403
