### ISSUE TITLE
Custom plugin - apply some changes

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#210]
### Description

* change 'in to' to 'into' in 'A plugin contains one or more features that can be easily plugged in to Handsontable.'

* **code style** anchor in the last paragraph redirects to 404.

> We support ECMAScript 6 and follow code style (inspired by Airbnb JavaScript Style), so those standards are required for the new plugins.

* I wouldn't call creating a new Handsontable plugin an easy task. Especially, as the Skeleton README is not sharing too many hints or tips.

> Writing a new plugin is not a difficult task, simply cloning the Skeleton template will give you a good starting point.

* I would remove the following paragraph. It does not share any valuable information and it indicates that we are willing to merge Clients' custom plugins to Handsontable just like that.

> Note that creating a plugin for personal needs is usually easier than writing an application destined for use by other developers. Such code has to be properly described, documented, frequently updated and supported. If you think that your plugin meets those requirements then consider sharing it with us. Get in touch for more details.

I think that we should be able to share some valuable information on how to create a plugin. Now it is just a page that tells me - visit this link (link to Skeleton).

### Links
* custom plugin tutorial - https://handsontable.com/docs/8.1.0/tutorial-custom-plugin.html
* support task (origin) - https://github.com/handsontable/support/issues/258

**Comment by swistach** [comment]
We have changed that guide in the new documentation.
