### ISSUE TITLE
Re-check links for handsontable-pro repository

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#218]
### Description
Hey @scarletfog!

@pnowak found that there are multiple links in our Release Notes that does not work (as they redirect to the handsontale-pro repository)

**Version of RN - broken link number**
6.2.0: #148,
6.1.0: #146, #149, #151, #154,
6.0.1: #142, #144,
5.0.2: #105, #107,
5.0.1: #29,
5.0.0: #87,
4.0.0: #72,
3.0.0: #65, #67, #69,
2.0.0: #43, #44, #47, #49,
1.18.0: #33,
1.16.0: #24,
1.15.1: #11, #23,
1.15.0: #13, #12, #15, #19, #6,
1.14.3: #2,

As the repo is no longer available I guess that we can just remove the link. It would be hard to find other links that were related to the task (issue report, pull request, commit).

### Links
release notes - https://handsontable.com/docs/8.1.0/tutorial-release-notes.html
support task (origin) - https://github.com/handsontable/support/issues/258

**Comment by swistach** [comment]
In the new documentation, we hid release notes for versions older than v7.4.0.
