### ISSUE TITLE
Faintly visible links elements

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#226]
### Description
As could be seen in the attached screenshot, the blue links on the grey background are hard to see.

![Zrzut ekranu 2020-10-22 o 08 34 39](https://user-images.githubusercontent.com/1555809/96834479-603dec00-1442-11eb-95c4-995d30c70350.png)

### Links
https://handsontable.com/docs/8.1.0/CellRange.html

**Comment by swistach** [comment]
In the new documentation, we changed the way we present types as links.
