### ISSUE TITLE
Incomplete description of the copyPaste option.

### ISSUE THREAD

**Issue by swistach** [handsontable/docs#24]
### Description
Current description: https://handsontable.com/docs/6.2.2/Options.html#copyPaste.
There is missing information about configuration object. Fortunately, all of the necessary details are available on a [tutorial page](https://handsontable.com/docs/6.2.2/CopyPaste.html).

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/handsontable/pull/7205
