### ISSUE TITLE
Introduction - rephrase the sentence

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#244]
### Description
I think that we should avoid using other projects names

> Handsontable is loved by users because it gives them the same experience as Google Sheets or Excel.

### Links
Introduction page - https://handsontable.com/docs/8.1.0/tutorial-introduction.html

**Comment by scarletfog** [comment]
@AMBudnik do you think, this will do:

_Handsontable is loved by users because it gives them the same experience as other popular spreadsheets on the market._

?

**Comment by AMBudnik** [comment]
or
...same experience as the spreadsheet that they already know.
...same experience as the best spreadsheets that there are.

all those options are true (and sound good).

**Comment by swistach** [comment]
The mentioned section is changed in new documentation: https://handsontable.com/docs/
