### ISSUE TITLE
demo-chromajs broken

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#25]
according to: https://github.com/handsontable/handsontable/issues/3060
____________

http://docs.handsontable.com/0.20.2/demo-chromajs.html
http://docs.handsontable.com/0.20.1/demo-chromajs.html

Uncaught TypeError: Cannot read property '1' of undefined
at `demo-chromajs.html:2088`

```
function updateHeatmap(change, source) { 
  // arguments: [true, undefined, undefined, undefined, undefined, undefined]
  if (change) {
	heatmap[change[0][1]] = generateHeatmapData.call(this, change[0][1]);
  } else {
```

**Comment by budnix** [comment]
Fixed in https://github.com/handsontable/docs/commit/aa96678d5fccd735414d737932ad49438da4d4c6.
