### ISSUE TITLE
Typo on page Copy & Paste

### ISSUE THREAD

**Issue by warpech** [handsontable/docs#256]
On page https://handsontable.com/docs/8.2.0/demo-copy-paste.html there is a typo:

> The CopyPaste plugin listens to the browser's `cop` and `cut` events, so if they are triggered, our implementation will copy or cut the selected data into the system clipboard.

Should be:

> The CopyPaste plugin listens to the browser's `copy` and `cut` events, so if they are triggered, our implementation will copy or cut the selected data into the system clipboard.

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/docs/pull/259
