### ISSUE TITLE
Read-only specific cells - demo update

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#26]
Source: http://docs.handsontable.com/0.20.2/demo-read-only.html (2nd example)

Should update `hot2.getData()` to `hot2.getSourceData()` according to changes made in [0.20.0](https://github.com/handsontable/handsontable/releases/tag/0.20.0)
Changed demo: http://jsfiddle.net/5tngx6wn/1/

Currently demo does not work.

**Comment by budnix** [comment]
Fixed in https://github.com/handsontable/docs/commit/ea764bc068627014288e7f0079c2722ae7ad7bb8.
