### ISSUE TITLE
Describe how to use batching and suspending

### ISSUE THREAD

**Issue by scarletfog** [handsontable/docs#261]
### Description
Recent changes for the upcoming 8.3.0 release include a new feature - batching
https://github.com/handsontable/handsontable/pull/7406

Write a page that advises how to use the new API methods.

This tutorial should be placed in the "developer guide" section as it is related to a more complex topic.
Somewhere around here: https://handsontable.com/docs/8.2.0/tutorial-cell-types.html

### Links
https://handsontable.com/docs/8.2.0/tutorial-cell-types.html (it should be placed above this, or below cells topic)

**Comment by aninde** [comment]
Tested during code freeze. Closing #261 as done.
