### ISSUE TITLE
minCols + object data

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#266]
### Description

We should add a note in the docs that the `minCols` does not work for object data. If added it returns an exception

> handsontable.full.js:79423 Uncaught Error: Cannot create new column. When data source in an object, you can only have as much columns as defined in first data row, data schema or in the 'columns' setting.If you want to be able to add new columns, you have to use array datasource.

### Links

* minCols - https://handsontable.com/docs/8.2.0/Options.html#minCols
* demo - https://jsfiddle.net/vbgw81he/1/

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7431
