### ISSUE TITLE
A page about modularization

### ISSUE THREAD

**Issue by scarletfog** [handsontable/docs#270]
### Description
Describe how to make use of the modularization. The page should be placed in the "developer guide".
Also, update the quickstart guide.

### Links
https://handsontable.com/docs/8.2.0/tutorial-quick-start.html (directly here)
https://handsontable.com/docs/8.2.0/tutorial-custom-build.html (somewhere in the "developer guide" section)

**Comment by aninde** [comment]
Tested during code freeze. 
Closed #270.
