### ISSUE TITLE
Grid sizing tutorial improvements

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#273]
### Description

* define what are 'fized parts' or 'fixed areas' as we call them later
![image](https://user-images.githubusercontent.com/10757813/103649395-ac3b0000-4f5e-11eb-9649-b4dc18b49440.png)
![image](https://user-images.githubusercontent.com/10757813/103649543-f0c69b80-4f5e-11eb-855e-63a4d06b2c27.png)

* add 'the' to the following statement
![image](https://user-images.githubusercontent.com/10757813/103649334-93324f00-4f5e-11eb-8487-7bb18f2302d0.png)

### Links

https://handsontable.com/docs/8.2.0/tutorial-grid-sizing.html

**Comment by swistach** [comment]
The mentioned section is changed in new documentation: https://handsontable.com/docs/grid-size/#what-if-the-size-is-not-set
