### ISSUE TITLE
DataSchema missing link

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#28]
where: https://docs.handsontable.com/0.21.0/Options.html#dataSchema
There's a missing link in description of dataSchema.

![zrzut ekranu 2016-01-28 o 12 34 57](https://cloud.githubusercontent.com/assets/10757813/12643331/c6155548-c5bb-11e5-8d78-df9a69cd93a4.png)

**Comment by budnix** [comment]
Fixed in https://github.com/handsontable/handsontable/commit/a88abcd7cbe04b81a05f91105265cbdf3d20366a.
