### ISSUE TITLE
[8.3.0] Suspend renderering & Modules - examples

### ISSUE THREAD

**Issue by aninde** [handsontable/docs#284]
### Description
1. Code examples are rendering with additional improper new line before and after example.

2. There is no counter of the lines (probably its caused by missed   `&lt;/` and `&gt;`
Note: Not all examples have those counter, so maybe we should standarized all of them.

Standard code example from out documentation
Without gutter
![Screenshot 2021-01-26 at 17 12 52](https://user-images.githubusercontent.com/30186818/105871588-c023d000-5ff9-11eb-95a9-5ad2bc27258a.png)

https://handsontable.com/docs/8.2.0/frameworks-wrapper-for-angular-installation.html
With gutter
https://handsontable.com/docs/8.2.0/tutorial-data-sources.html
![Screenshot 2021-01-26 at 16 57 14](https://user-images.githubusercontent.com/30186818/105870475-9a49fb80-5ff8-11eb-9ee7-49068cc3cea8.png)

**Suspend renderering code example**
![Screenshot 2021-01-26 at 16 56 29](https://user-images.githubusercontent.com/30186818/105870519-a635bd80-5ff8-11eb-8616-1f98697bd66d.png)

### Your environment

* Handsontable version: 8.3.0
* Browser Name and version: Chrome Beta  88.0.4324.96 and IE 11
* Operating System: macOs Big Sur and Windows 10

**Comment by scarletfog** [comment]
As discussed, looks as if the gutter is present only for editable demos, not code blocks.

You can check the code samples for example here:
https://handsontable.com/docs/8.2.0/demo-data-validation.html

Only the one you can `edit` has this counter. 

for the extra space on top and bottom - I will check what's missing 🔎

**Comment by aninde** [comment]
Created & tested during code freeze of the v8.3.0.
Closed #284.
