### ISSUE TITLE
 Property 'root' does not exist on type... (root="hot")

### ISSUE THREAD

**Issue by yzaroui** [handsontable/docs#303]
Hello,

The prop `root` used in this example does not exist in the HotTable props definition.

https://github.com/handsontable/docs/blob/a144fa04f22d1e0da7b75917c2403a5334b09545/tutorials/wrapper-for-react-simple-examples.html#L172

**Comment by AMBudnik** [comment]
Issue moved to [handsontable/handsontable #7609](https://github.com/handsontable/handsontable/issues/7609) via [**ZenHub**](https://www.zenhub.com/)
