### ISSUE TITLE
Change in docs related to bug fixes in sorting checkboxes

### ISSUE THREAD

**Issue by wszymanski** [handsontable/docs#305]
### Description
[Changes for next release](https://github.com/handsontable/handsontable/pull/7684) related to sorting checkboxes should be described properly.

**Comment by aninde** [comment]
Docs adjustment in the `tutorial-cell-types.html` fixes are very necessary and well described. 
I wonder if it is worth adding `the code` and a `link to jsfiddle`, to be consistent with the rest of the content. 

Now it looks:
![image](https://user-images.githubusercontent.com/30186818/117132388-15af0c00-ada3-11eb-9bc1-b9ceef5ea04c.png)

**Comment by aninde** [comment]
@wszymanski thank you for the fast adjustments. Corrections will be released with v8.4.0

<img width="881" alt="Screenshot 2021-05-05 at 14 22 08" src="https://user-images.githubusercontent.com/30186818/117140305-8b1fda00-adad-11eb-8b3c-83f85ac152f7.png">

**Comment by swistach** [comment]
Released in v8.4.0
