### ISSUE TITLE
Broken URL to older versions

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#31]
Place to look: https://docs.handsontable.com/0.22.0/tutorial-release-notes.html 

broken versions: 
from 0.20.1 (https://docs.handsontable.com/0.20.1/tutorial-release-notes.html)
to oldest 0.15.0-beta 1 (https://docs.handsontable.com/0.15.0-beta1/tutorial-release-notes.html)

**Comment by krzysztofspilka** [comment]
There was no such page in the previous versions of docs. It's a correct
behavior.
12 lut 2016 14:42 "Aleksandra Budnik" <notifications@github.com> napisał(a):
