### ISSUE TITLE
Incomplete definition of beforeRender hook.

### ISSUE THREAD

**Issue by swistach** [handsontable/docs#31]
Our current description doesn't contain information about a second argument - which allows skipping the next render cycle.

Current state: https://handsontable.com/docs/Hooks.html#event:beforeRender

Source code: https://github.com/handsontable/handsontable/blob/7.1.0/src/3rdparty/walkontable/src/tableRenderer.js#L51

Updated source code: https://github.com/handsontable/handsontable/blob/master/src/3rdparty/walkontable/src/table.js#L278

**Comment by scarletfog** [comment]
@swistach the to tableRenderer is no longer accessible.

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7209
