### ISSUE TITLE
Remove tutorials and mentions for the removed plugins

### ISSUE THREAD

**Issue by budnix** [handsontable/docs#311]
### Description
In the upcoming v9 version the _HeadersTooltips_ and _ObserveChanges_ plugins are removed. Is a need to update the docs.

### Your environment

* Handsontable version: 9.0.0
* Browser Name and version:
* Operating System:

**Comment by jansiegel** [comment]
▶️ https://github.com/handsontable/docs/commit/305fa485137691c022cbcd5dffd6ef09bd4823cd

**Comment by AMBudnik** [comment]
Closed as done.
