### ISSUE TITLE
Post-9.0.0 documentation improvements

### ISSUE THREAD

**Issue by jansiegel** [handsontable/docs#314]
### Description
Things that need fixing after the release of `9.0.0`:

- [x]  Deprecated section styling missing (?) [[internal slack discussion](https://handsoncode.slack.com/archives/C02219AACJV/p1622546659007900)]
- [x] Unwanted characters in the migration guide [[internal slack discussion](https://handsoncode.slack.com/archives/C02219AACJV/p1622546881008800?thread_ts=1622546659.007900&cid=C02219AACJV)]
- [x] Missing "Edit in JSFiddle" button in the HyperFormula Integration page [[internal slack discussion](https://handsoncode.slack.com/archives/C02219AACJV/p1622551664017100?thread_ts=1622546659.007900&cid=C02219AACJV)]
- [x] `beforeAutofill` styling not working properly [[internal slack discussion](https://handsoncode.slack.com/archives/C02219AACJV/p1622546943010000)]

**Comment by swistach** [comment]
We changed all of the mentioned things in the new documentation.
