### ISSUE TITLE
Documentation for comments is wrong

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/docs#32]
### Description

Docs for grid prop `comments`: https://handsontable.com/docs/6.2.2/Options.html#comments

Says that you can pass comment objects and has this example:
```
// or
// enable comments plugin and add predefined comments
comments: [
  {
    row: 1,
    col: 1,
    comment: {
      value: "Test comment"
    }
  }
],
```
But this appears to be wrong, as the demo correctly shows you need to pass `comment` objects in the `cells` config: https://handsontable.com/docs/6.2.2/demo-comments_.html

Also the `comments` config seems to have a property `displayDelay`.

**Comment by AMBudnik** [comment]
This issue just got closed with https://github.com/handsontable/handsontable/issues/6125
