### ISSUE TITLE
The focus from input in a header is stolen - version IE and Edge

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#34]
It's related to this issue - https://github.com/handsontable/handsontable/issues/5820

And maybe this bug will be resolved by `listen/unlisten` in the same demo - https://handsontable.com/docs/6.2.2/demo-filtering.html#custom-implementations

**Comment by scarletfog** [comment]
I am not sure we can do much docs-wise here. Either we fix the issue, let it be, or try to find a workaround just for the edge. I would close this issue, @AMBudnik ?

**Comment by AMBudnik** [comment]
Hi @scarletfog we need to investigate this subject. We have two possible scenarios here
- we do have an issue that is described by this demo (so we make no changes to the docs, just report the issue on /handsontable)
- the demo is insufficient and it needs adjustments

**Comment by scarletfog** [comment]
I played with the demo more and it appears that it sometimes loses the focus anyway, not only on edge (Chrome).
It does not happen when I navigate with `tab` button, maybe you will find this information helpful @pnowak

**Comment by AMBudnik** [comment]
@scarletfog Piotr confirmed that this is an issue with Handsontable https://github.com/handsontable/handsontable/issues/5820
We can close this topic.
