### ISSUE TITLE
Change formatting for the TrimRows page

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#35]
https://handsontable.com/docs/7.0.0/TrimRows.html looks odd.

![image](https://user-images.githubusercontent.com/10757813/53886091-84577a00-401f-11e9-8e45-f527689f1fc9.png)

there are too many broken lines.

**Comment by AMBudnik** [comment]
It's related to the way we write the comments in the code.

Should get fixed with https://handsontable.com/docs/7.0.0/Hooks.html#event:afterListen

**Comment by scarletfog** [comment]
As discussed in a similar issue:
https://github.com/handsontable/docs/issues/134

This will not be a trivial change, we should find a way to unify the formatting of descriptions across the whole documentation.

**Comment by swistach** [comment]
The mentioned section is changed in new documentation: https://handsontable.com/docs/api/trim-rows/
