### ISSUE TITLE
Dropdown 'filter' definition

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#37]
We could add more details about what's `filter` for in the dropdown cell type.
URL: http://docs.handsontable.com/0.26.0/demo-dropdown.html

Jon's proposition:

> If [filter] defined as 'true', when the user types into the input area the Autocomplete's suggestion list is updated to only include those choices starting with what has been typed; if defined as 'false' all suggestions remain shown, with those matching what has been typed marked in bold.
_source: https://forum.handsontable.com/t/behaviour-of-dropdown-type-filter-option/484/3_

**Comment by budnix** [comment]
Fixed in https://github.com/handsontable/handsontable/commit/53313af3165f0d6c130e30580d1f9ad6cfea89c3
