### ISSUE TITLE
An outdated info in "Demos / Rows and columns / Moving" section

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/docs#4]
@arogachev commented on [Wed Feb 28 2018](https://github.com/handsontable/handsontable/issues/4855)

https://docs.handsontable.com/0.36.0/demo-moving.html

This part:

```
The draggable move handle appears:

- in the right part of the column header,
- in the top part of the row header.
```

is outdated and confusing.

That how it was in previous versions:

https://docs.handsontable.com/0.15.1/demo-moving-rows-and-columns.html

![Version 0.15.1](https://user-images.githubusercontent.com/8326201/36776448-0418ba1a-1c90-11e8-823f-72e961633e33.gif)

That how it works now:

https://docs.handsontable.com/0.36.0/demo-moving.html

![Version 0.36.0](https://user-images.githubusercontent.com/8326201/36776493-35393944-1c90-11e8-8314-a52ecc9ed91f.gif)

---

@AMBudnik commented on [Wed Feb 28 2018](https://github.com/handsontable/handsontable/issues/4855#issuecomment-369238997)

Thank you for spotting that! That's true. The information placed in the tutorial is outdated.

**Comment by AMBudnik** [comment]
Updated link https://handsontable.com/docs/7.1.0/demo-moving.html but the description is still wrong.

When we click on the header the little hand appears and we can click & drag clicking anywhere in the column header body.

**Comment by scarletfog** [comment]
Done :)
