### ISSUE TITLE
`autoRowSize` information is misleading.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/docs#40]
[The documentation](https://handsontable.com/docs/7.0.0/Options.html#autoRowSize) wrongly suggests, that the AutoRowSize plugin is enabled by default, while it's not: https://jsfiddle.net/qnuj5sLg/.

**Comment by scarletfog** [comment]
@jansiegel as I read: "Enables or disables `AutoRowSize` plugin. Default value is `undefined`, which has the same effect as false (disabled)"

I think we should close this issue.

**Comment by jansiegel** [comment]
> @jansiegel as I read: "Enables or disables `AutoRowSize` plugin. Default value is `undefined`, which has the same effect as false (disabled)"
> 
> I think we should close this issue.

It also states: `Default Value: {syncLimit: 500}`, so there's a mismatch.

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/handsontable/pull/7210
