### ISSUE TITLE
new cellRander function,editor has problem

### ISSUE THREAD

**Issue by suheweiyang** [handsontable/docs#42]
code:
export default {
    name: 'App',
    components: {
      HotTable
    },
    data() {
      return {
        data:[
         [{text:'aaa',bgColor:'#ba87ee'},{text:'bbb',bgColor:'#24f79e'}],
         [{text:'aaa',bgColor:'#ba87ee'},{text:'bbb',bgColor:'#24f79e'}],
         [{text:'aaa',bgColor:'#ba87ee'},{text:'bbb',bgColor:'#24f79e'}],
         [{text:'aaa',bgColor:'#ba87ee'},{text:'bbb',bgColor:'#24f79e'}],
        ],
        hotSettings: {
          columns: [
                      {renderer:this.cellRander,editor:CustomEditor,editorOption:'text'}, 
                      {renderer:this.cellRander,editor:'text'},{}],
     
       ...............
      
            }
          }
        },
      }
    },
    mounted() {
    
    },
    methods: {
      cellRander(instance, td, row, col, prop, value, cellProperties){
        Handsontable.renderers.TextRenderer.apply(this, arguments);
        // console.log('instance',instance,/\n/,'td', td,'row', row,'col', col,'prop', prop,'value', value,'cellProperties', cellProperties)
        value.text?td.innerText=value.text:'';
        td.style.background=value.bgColor;
        td.setAttribute('text',value.text);
        return td
      },
    }
  }

//==========when i  editor the cells it is a object, how to deal width this??

![20190514172346](https://user-images.githubusercontent.com/29392743/57686984-2e313380-766d-11e9-9726-33231c19a80d.png)
![20190514172418](https://user-images.githubusercontent.com/29392743/57686991-325d5100-766d-11e9-8e57-58a72a201032.png)

**Comment by suheweiyang** [comment]
really appreciate

**Comment by AMBudnik** [comment]
Hey @suheweiyang 

data should be an array of objects or an array of arrays. In your example, it is an array of objects held in an array.

**Comment by suheweiyang** [comment]
i knew it  but i need other attrs , i can set background color when render cells,

**Comment by suheweiyang** [comment]
> Hey @suheweiyang
> 
> data should be an array of objects or an array of arrays. In your example, it is an array of objects held in an array.

do you have other way to di it?

**Comment by AMBudnik** [comment]
You can pass metadata or classes via [cells ](https://handsontable.com/docs/7.0.3/Options.html#cells)method. Then you won't need the renderer. Here is a complete example http://jsfiddle.net/swx43n2p/

**Comment by suheweiyang** [comment]
oh,thanks, i'll try ,its dinner time

**Comment by suheweiyang** [comment]
> You can pass metadata or classes via [cells ](https://handsontable.com/docs/7.0.3/Options.html#cells)method. Then you won't need the renderer. Here is a complete example http://jsfiddle.net/swx43n2p/

how to get vue data in custom contextmenu,
![20190516142835](https://user-images.githubusercontent.com/29392743/57831504-e8e54100-77e7-11e9-878c-1ed7a363418d.png)

**Comment by suheweiyang** [comment]
> You can pass metadata or classes via [cells ](https://handsontable.com/docs/7.0.3/Options.html#cells)method. Then you won't need the renderer. Here is a complete example http://jsfiddle.net/swx43n2p/

my fault ,i did not read it carefully , so thank you very much

**Comment by AMBudnik** [comment]
Not a problem :)

ps. I can ask you to post all future posts on the main repository here https://github.com/handsontable/handsontable or just send them straight to me at support@handsontable.com? This repo is only for documentation

**Comment by suheweiyang** [comment]
> Not a problem :)
> 
> ps. I can ask you to post all future posts on the main repository here https://github.com/handsontable/handsontable or just send them straight to me at [support@handsontable.com](mailto:support@handsontable.com)? This repo is only for documentation

ok,i'll close it.
