### ISSUE TITLE
Highlight current row INCLUDING current cell

### ISSUE THREAD

**Issue by g0nP** [handsontable/docs#42]
Hi, I want to highlight an entire row when I select any of its cells.

I'm using "currentRowClassName: 'currentRow'," as suggested in the tutorial, but it doesn't applies the css class to the selected cell.

Is there a way to achieve this?
Thanks in advance!

**Comment by AMBudnik** [comment]
Hi @g0nP 

Usually if some styles are not working in Handsontable you can refer to one or more elements above to get more precise CSS path.

Please check this demo: http://jsfiddle.net/sbLh2mse/

You have to call `.handsontable .currentRow` to make it work.

**Comment by g0nP** [comment]
Hi @AMBudnik! Thanks for answering!

I tried your solution but I'm having the same results. When I click on a cell the background color applies to the entire row but not to the cell I clicked.

In your fiddle for example, I click on the 2011 cell and the background color of the car and prices cells turns yellow. However, the background color of the 2011 cell I clicked remains white.

I'm trying to find a way to change the background color of the clicked cell as well.

**Comment by AMBudnik** [comment]
You're right. I guess that the easiest way would be to overwrite the `.current` class background.

here's an example:
http://jsfiddle.net/kof5stvd/

and the code will be

```
.handsontable td.currentRow, .handsontable td.current {
  background: yellow
}
```

**Comment by g0nP** [comment]
Thank you ver much @AMBudnik. It works now!

**Comment by AMBudnik** [comment]
You,'re welcome :) Happy I could help.
