### ISSUE TITLE
Incomplete definition of some hook

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#44]
Our current documentation does not contain information that some hooks can return `false` (` Boolean`):

`afterValidate`,
`beforeChange`,
`beforeColumnMove`,
`beforeColumnSort`.

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/handsontable/pull/7211

**Comment by aninde** [comment]
@scarletfog  In the case of `afterValidate` we have a repetition

 
<img width="534" alt="Screenshot 2020-09-30 at 17 11 05" src="https://user-images.githubusercontent.com/30186818/94704411-2b0d1500-0340-11eb-8d58-c4e20885ae1c.png">
