### ISSUE TITLE
Custom build docs don't work on the develop branch

### ISSUE THREAD

**Issue by TRManderson** [handsontable/docs#47]
The "Custom build" docs say to use grunt, but all grunt tasks have been removed from HoT in the develop branch. I don't know what the correct build process is now.

**Comment by AMBudnik** [comment]
Hi @TRManderson 
We are currently moving to another way of building custom packages. Hopefully today we will be able to release version 0.32.0-beta1 with a major change, which also changes the way of building packages. Please stay tuned with https://docs.handsontable.com/tutorial-release-notes.html
