### ISSUE TITLE
Uncaught TypeError on copy-paste on the demo page

### ISSUE THREAD

**Issue by swistach** [handsontable/docs#48]
The issue which has been added by @krzysztofspilka: [#3862](https://github.com/handsontable/handsontable/issues/3862)
### Description

There is an error "Uncaught TypeError: Cannot read property '0' of undefined(…)" being thrown on copy-paste in a demo about conditional formatting.

### Steps to reproduce

1. Go to https://docs.handsontable.com/demo-conditional-formatting.html
2. Copy everything
3. Paste anywhere below a first row

### Demo

https://gyazo.com/2d912511298f88fb37566fb81de83d05

### Solution
In file: [/tutorials/conditional-formatting.html](https://github.com/handsontable/docs/blob/0.32.0/tutorials/conditional-formatting.html#L93) should be:
``` javascript
var getData = this.instance.getData();

if (row === 0 || (getData[row] && getData[row][col] === 'readOnly')) {
   ...
```

**Comment by wszymanski** [comment]
Fixed.
