### ISSUE TITLE
afterPluginsInitialized does not work

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#49]
@AMBudnik commented on [Fri Apr 14 2017](https://github.com/handsontable/handsontable/issues/4196)

### Description

`afterPluginsInitialized `does not work

### Steps to reproduce

1. Check the console. You should get a log `done` after loading all plugins (like `columnSorting`).

### Demo

http://jsfiddle.net/handsoncode/r79b0Lx7/

### Your environment
* Handsontable version: 0.31.2 / 1.10.2
* Browser Name and version: Chrome 56
* Operating System: Windows 10

**Reported at** https://forum.handsontable.com/t/cant-add-callback-for-afterpluginsinitialized-hook/918

---

@Rex90 commented on [Mon Nov 20 2017](https://github.com/handsontable/handsontable/issues/4196#issuecomment-345723528)

I agree - this doesn't work with 1.14.3. Consequently I dont seem to be able to do;

`hot.getPlugin("collapsibleColumns").settings`

---

@AMBudnik commented on [Thu Feb 01 2018](https://github.com/handsontable/handsontable/issues/4196#issuecomment-362221575)

The callback still dos not work (updated 0.35.1)

---

@AMBudnik commented on [Mon Apr 30 2018](https://github.com/handsontable/handsontable/issues/4196#issuecomment-385373635)

It doesn't work in v `2.0.0` or any version before. Maybe we're missing something here? If it's not a bug we need to describe it in the docs.

---

@hassanrehman commented on [Fri Jun 15 2018](https://github.com/handsontable/handsontable/issues/4196#issuecomment-397618751)

Still doesn't work.

---

@talamaska commented on [Wed May 08 2019](https://github.com/handsontable/handsontable/issues/4196#issuecomment-490446548)

in version 7.0.2 still afterPluginsInitialized is not fired

---

@talamaska commented on [Wed May 08 2019](https://github.com/handsontable/handsontable/issues/4196#issuecomment-490447573)

@AMBudnik Could you please have someone look into this issue it is reported 2 years ago and the bug is still valid

---

@talamaska commented on [Wed May 08 2019](https://github.com/handsontable/handsontable/issues/4196#issuecomment-490459786)

the funny thing is that when consoled in _base.js or in pluginHooks.js, the hook is ran, but doesn't propagate to my angular component at all tried different ways to bind it - via attribute on the hot-table component or via settings param. none of them is fired. Going deeper in code - 
```
key: "run",
    value: function run(context, key, p1, p2, p3, p4, p5, p6) {
{
var globalHandlers = this.globalBucket[key];
...
```
the globalHandlers is an empty array so nothing gets called here for key afterPluginsInitialized
```
var res = globalHandlers[index].call(context, p1, p2, p3, p4, p5, p6);
```
so has to be something inside handsontable, not in the angular component.

---

@AMBudnik commented on [Mon May 13 2019](https://github.com/handsontable/handsontable/issues/4196#issuecomment-491762557)

You're right it still doesn't work http://jsfiddle.net/handsoncode/b4mh3sav/ (v `7.0.2`) and it's broken for Vanilla. If it doesn't work for vanilla it won't work for the wrappers.

I see it is called in the source code. I've built a plain example and run in on a local server and the hook is called.

![image](https://user-images.githubusercontent.com/10757813/57610763-afa39b80-7571-11e9-88f8-e66aa2b15883.png)

But it never alerts me about it

```js
var hot = new Handsontable(box, {
    data: [[1,3],[5,7]],
    licenseKey: 'non-commercial-and-evaluation',
    columnSorting: true,
    afterPluginsInitialized: function(){
      alert('afterPluginsInitialized')
    }
})
```

---

@wojciechczerniak commented on [Mon May 13 2019](https://github.com/handsontable/handsontable/issues/4196#issuecomment-491788060)

That's because this hook is run internally on `beforeInit` hook, before settings are used. 
You can add hook before Handsontable is initialized: http://jsfiddle.net/qo2weksy/2/

Might work better after #5933. 

---

@AMBudnik commented on [Mon May 13 2019](https://github.com/handsontable/handsontable/issues/4196#issuecomment-491789819)

Hey @talamaska please try @wojciechczerniak approach and let me know if it works for you

**Comment by AMBudnik** [comment]
This hook runs only on the initialization.
We should change the description.

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7212
