### ISSUE TITLE
After changes from empty string to null

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#53]
in https://github.com/handsontable/handsontable/pull/6031
we need to change demo from this https://handsontable.com/docs/7.1.0/demo-data-validation.html
Because in this demo use `string` method `charAt`, and after `delete` we have `bug` - `Uncaught TypeError: Cannot read property 'charAt' of null`.

**Comment by scarletfog** [comment]
@pnowak I can't reproduce the issue, could you please help me a bit?

**Comment by AMBudnik** [comment]
I got this error

![Zrzut ekranu 2020-08-19 o 09 48 15](https://user-images.githubusercontent.com/10757813/90607150-201f7a80-e201-11ea-86d5-eb208a684af7.png)

when I 
1. Used this demo https://jsfiddle.net/odc4b6ny/
2. Removed a row via context menu
3. used CTRL/CMD + Z to undo

but maybe @pnowak will be able to tell why we get this error.

**Comment by scarletfog** [comment]
Thank you @AMBudnik! I missed `CMD+ Z` part 😅 .
Ok, I see, we lose names and e-mail so it breaks but I don't know how to fix it ad hoc so let's wait for Piotr.

**Comment by pnowak** [comment]
This error has a source of the changes a default value for the empty cells. 

Earlier the default value was an empty string. After this PR https://github.com/handsontable/handsontable/pull/6031, the default value is `null`. 
In the demo, we use `chartAt` which is a method for the `string` type. So `null` doesn't have this method.

**Comment by AMBudnik** [comment]
@scarletfog we'll send you an updated demo (possibly on Monday / Tuesday).

**Comment by AMBudnik** [comment]
@scarletfog here's our proposition https://jsfiddle.net/qbftpsv7/

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/docs/pull/145
