### ISSUE TITLE
Minor tutorial issue, wrong URL

### ISSUE THREAD

**Issue by dborisog** [handsontable/docs#53]
on https://docs.handsontable.com/0.34.4/tutorial-features.html

Formulas | Use formulas in cells to perform calculations.

links to Filtering page, which is clearly a mistake.
( https://docs.handsontable.com/pro/1.14.2/demo-filtering.html )

I haven't checked other links, so not sure if more invalid links are present on the page. The actual link to "Filtering" page is valid.

**Comment by AMBudnik** [comment]
Thank you for spotting that! Yes, that's a mistake.

**Comment by AMBudnik** [comment]
Still an issue in 4.0.0 CE/PRO

**Comment by AMBudnik** [comment]
Works fine in 5.0.0
again thanks for sharing @dborisog
