### ISSUE TITLE
Context menu options string for hide/show columns

### ISSUE THREAD

**Issue by craigbenstock** [handsontable/docs#55]
### Description
Context menu has built in options for hide column and show column, but I can't find in the documentation the string with which to specify them.

I would like to limit the context menu to only the show and hide column options.

eg, contextMenu: ['hide_col', 'show_col']

Following the convention of other options I have tried using:

- 'hide'
- 'hide_column'
- 'hide_col'
- 'col_hide'

all to no avail.

Please let me know if there is an option for this, or if one can be added.

### Steps to reproduce
Not relevant.

### Demo
See screenshots

![image](https://user-images.githubusercontent.com/16646141/61281448-8e4d6e80-a7b1-11e9-813f-9a4706d6dd4c.png)

![image](https://user-images.githubusercontent.com/16646141/61281501-a1603e80-a7b1-11e9-9911-c3d39eaef5f1.png)

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by scarletfog** [comment]
Upon investigation I found out that we had already mentioned `hiding`:
![image](https://user-images.githubusercontent.com/20072336/92125376-42b7b300-edff-11ea-9fba-2ac589c735b3.png)

@AMBudnik does it fit the need?

**Comment by AMBudnik** [comment]
@scarletfog yes, we can close it.
