### ISSUE TITLE
Comments docs are missing readOnly option

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/docs#56]
We can set `comment` read only with:
```
comment: {
  value: 'Some comment', 
  readOnly: true
}}
```

but https://handsontable.com/docs/7.1.0/Options.html#readOnly mentions only Cell.

And comments docs page does not have this explained.

Example: https://jsfiddle.net/povhweL6/

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7214

**Comment by aninde** [comment]
I can't find this change in the documentation for version 8.1.0.

**Comment by scarletfog** [comment]
You are right @aninde it is done only partially - https://github.com/handsontable/handsontable/pull/7214/files
And it misses this change https://github.com/handsontable/docs/pull/141 

Probably I forgot to merge it.

I will reopen the issue and it will go with the next release.

**Comment by scarletfog** [comment]
Small update - part of it was done here: https://github.com/handsontable/docs/pull/141
