### ISSUE TITLE
Little styling issue

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#6]
In [numeric cell type](http://docs.handsontable.com/demo-numeric.html) demo, `edit on fiddle`button does not hover properly. Hovering changes font color instead of background.

Other cell type menu options are fine.

![rrr](https://cloud.githubusercontent.com/assets/10757813/7565207/5de14f86-f7ee-11e4-8491-1cbef036dfb9.gif)

**Comment by budnix** [comment]
Works fine :ok:
