### ISSUE TITLE
Wrappers demos: Setting up a new culture

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#62]
As mentioned in the following topic https://github.com/handsontable/handsontable/issues/6145 setting up a new `culture` can cause some issues.
We should add an example to the documentation to guide the users on how to proceed with this task.

The subject related to React, but as we try to keep the consistency within all the wrappers I think that the example should also be added to the Angular and Vue examples sections.

Side notes from me (@scarletfog)
The examples should be added to the wrappers section, around here: https://handsontable.com/docs/8.1.0/frameworks-wrapper-for-angular-installation.html

**Comment by AMBudnik** [comment]
@scarletfog we really need this one. I just got another question about setting up culture in Angular https://forum.handsontable.com/t/numericformat-german/4795/4 and it not that easy.

**Comment by scarletfog** [comment]
@AMBudnik I added a high priority label and I will start the investigation as soon as possible.

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/docs/pull/253
