### ISSUE TITLE
Fill 'select' cell type description with missing value option

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#64]
The `select` cell type is described to accept only an array of strings as a value. 

![Zrzut ekranu 2019-07-26 o 14 54 56](https://user-images.githubusercontent.com/10757813/61952911-5e724800-afb5-11e9-8ff4-b848c860953c.png)

However, it also accepts an array of numbers https://jsfiddle.net/AMBudnik/qxyc1kdz/
![Zrzut ekranu 2019-07-26 o 14 57 47](https://user-images.githubusercontent.com/10757813/61953082-ca54b080-afb5-11e9-862f-11f2af52e7ce.png)

We should add this information to the [documentation](https://handsontable.com/docs/7.1.0/Options.html#selectionOptions) and adjust the [definition file](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1766).

**Comment by swistach** [comment]
Indeed, you can even put there any type, but finally, it will be parsed into a string (through the `toString()` method).
HTMLOptionElement in its `value` property stores `DOMString` -> https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement. I thing we should leave here `string[]` as a correct type.
