### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/docs#68]
- [ ] Handsontable CE and Pro are mentioned, we should remove those
- [ ] Check if `brew ruby` is required ? We should add an installation step
- [ ] Check if `node-sass` is required ? We should add a step

**Comment by scarletfog** [comment]
I no longer see PRO/CE mentions in the README file. They appear in previous versions but is it an issue?. 
Ruby and Sass were added 👍 . I will close this issue, please re-open if needed.
