### ISSUE TITLE
Moving documentation update

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/docs#7]
@wszymanski commented on [Mon Jan 09 2017](https://github.com/handsontable/handsontable/issues/3983)

### Description

**[Moving demo](http://docs.handsontable.com/0.29.2/demo-moving.html)** and **[manualColumnMove](http://docs.handsontable.com/0.29.2/Options.html#manualColumnMove)** section of Handsontable **Options** need to be updated. There is no information about logical indexes and outdated information about drag mechanism.

---

@wszymanski commented on [Mon Jan 09 2017](https://github.com/handsontable/handsontable/issues/3983#issuecomment-271291473)

connected to #3822

**Comment by wszymanski** [comment]
Related to: https://github.com/handsontable/docs/commit/84727fa8f008a9c84aa21f32bf868442a2157e9a

**Comment by scarletfog** [comment]
@wszymanski is this issue still relevant?
Since 8.0.0 I see that the diagram was added and it is neatly described. However, I am not sure about this: https://handsontable.com/docs/8.0.0/Options.html#manualColumnMove though

**Comment by wszymanski** [comment]
@scarletfog It isn't relevant. It can be closed.

**Comment by scarletfog** [comment]
Thanks @wszymanski! I am closing this issue.
