### ISSUE TITLE
Wrong link to quick setup in NestedRows in Api Reference / Options

### ISSUE THREAD

**Issue by aninde** [handsontable/docs#73]
On site
https://handsontable.com/docs/7.1.1/Options.html#nestedRows
link to setup of Nested rows opens draft, local version, incorrect.

Link should lead to [Demo Nested Rows](https://handsontable.com/docs/7.1.1/demo-nested-rows.html)

**Comment by scarletfog** [comment]
This issue no longer occurs in 8.0.0 => https://handsontable.com/docs/8.0.0/Options.html#nestedRows
