### ISSUE TITLE
Replace the `format` with `numericFormat` in date demos after 0.35.0

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#77]
We need to replace all date demos from 0.35.0+ with the `numericFormat` instead of `format`.

Now our demos https://docs.handsontable.com/pro/6.0.0/demo-date.html does not show the currency attached.

![image](https://user-images.githubusercontent.com/10757813/46198280-60736800-c30c-11e8-99d6-c1c151abfc60.png)

https://docs.handsontable.com/pro/6.0.0/demo-date.html

ps. [numeric demos](https://docs.handsontable.com/pro/6.0.0/demo-numeric.html) are fine

**Comment by jansiegel** [comment]
Fixed the problem in the latest versions of docs and docs-pro.

**Comment by AMBudnik** [comment]
Thanks @jansiegel
