### ISSUE TITLE
Undo/Redo is enabled by default

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/docs#8]
@andrewQwer commented on [Tue Apr 11 2017](https://github.com/handsontable/handsontable/issues/4183)

Hi,

Documenation says the following (http://docs.handsontable.com/0.31.2/Options.html#undo):
```
If true, undo/redo functionality is enabled.

Default Value:
undefined
```

But undo/redo works even if I don't initialize `undo` option on initialization. It becomes disabled only if I set `undo: false` manually. Should the documenation say `Default value: true`?

Short example: http://jsfiddle.net/s6t768pq/609/

---

@AMBudnik commented on [Wed Apr 12 2017](https://github.com/handsontable/handsontable/issues/4183#issuecomment-293497930)

It is set to `undefined` but it looks like that some other hook (maybe the change hook) is enabling it.

Thanks for sharing. This one should be checked.

---

@AMBudnik commented on [Fri Apr 27 2018](https://github.com/handsontable/handsontable/issues/4183#issuecomment-384948967)

Did not change in `2.0.0`

---

@AMBudnik commented on [Mon Aug 27 2018](https://github.com/handsontable/handsontable/issues/4183#issuecomment-416211500)

There is actually a note in the _handsontable.full.js_ file that says

>  @description
>  * Handsontable UndoRedo plugin allows to undo and redo certain actions done in the table.
>  *
>  * __Note__, that not all actions are currently undo-able. The UndoRedo plugin is **enabled by default.**

We should add an information in the docs that even when [`Default Value: undefined`](http://jsfiddle.net/rpg67khe/) the undo action is enabled by default.

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/handsontable/pull/7191
