### ISSUE TITLE
We should hide/remove DataMap from the documentation

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#82]
We should remove the following page with all [inbounding links](https://handsontable.com/docs/7.2.1/Core.html#getCopyableData) as it is private and should not be a part of the official documentation.

src https://handsontable.com/docs/7.2.1/DataMap.html

**Comment by scarletfog** [comment]
@AMBudnik everything that has `(see DataMap#xyz)`?

**Comment by AMBudnik** [comment]
Hi @AMBudnik I've discussed the subject with @budnix and decided to keep the DataMap info as it is. I'm closing this ticket.
