### ISSUE TITLE
Redirect known-limitations to licensing

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/docs#85]
In branch a [8.0.0-licensing](https://github.com/handsontable/docs/tree/8.0.0-licensing) I removed known-limitations.html file and moved all the content to licensing.html.

**Todo:**
Please make a permanent redirect for handsontable.com/docs/tutorial-known-limitations.html to tutorial-licensing.html.

**Comment by budnix** [comment]
Merged with draft-next branch https://github.com/handsontable/docs/commit/5354439ce1d04ea9a452cf98c50ce96da49eaab7. Also, a redirect is configured and will take effect from version 7.3.0.
