### ISSUE TITLE
404 in cells section

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#93]
In section https://handsontable.com/docs/7.3.0/Options.html#cells 
both links `array of objects` https://handsontable.com/tutorial-data-sources#page-object
and  `array of arrays` https://handsontable.com/tutorial-data-sources#page-array don't work. 

We need to change to https://handsontable.com/docs/7.3.0/tutorial-data-sources.html#page-object and https://handsontable.com/docs/7.3.0/tutorial-data-sources.html#page-array

This problem exists in all versions of our documentation, i.e. since version 1.14.0.

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/handsontable/pull/7270
