### ISSUE TITLE
No bootstrap demo on Bootstrap example

### ISSUE THREAD

**Issue by aninde** [handsontable/docs#94]
https://handsontable.com/docs/7.3.0/tutorial-bootstrap.html
> This page demonstrate example of using Handsontable with Bootstrap. 

There is no example.

We should add it. 

### Print screen:
![Screenshot 2020-01-27 at 14 29 27](https://user-images.githubusercontent.com/30186818/73178423-80d65100-4111-11ea-93e2-387584bc5bd1.png)

**Comment by AMBudnik** [comment]
That's a quite old issue @aninde ^^
https://github.com/handsontable/docs/issues/48

**Comment by aninde** [comment]
@AMBudnik thank you. I close as a duplicate.
