### ISSUE TITLE
Absence of onCellDblClick description in documentation

### ISSUE THREAD

**Issue by aninde** [handsontable/docs#95]
We plan to describe `onCellDblClick` in the release notes after the release of version 7.4. and we don't have a description of it in the documentation or an example in callbacks 
https://handsontable.com/docs/7.3.0/tutorial-using-callbacks.html

We should describe something that can probably then be sought after by customers.

We were asked about this before https://github.com/handsontable/handsontable/issues/4840

And there were some questions on SO:
https://stackoverflow.com/questions/42362609/handsontable-modify-doubleclick-event
https://stackoverflow.com/questions/44535921/handsontable-update-css-property-of-cell-and-maintain-current-cell-renderer?rq=1

**Comment by budnix** [comment]
The `onCellDblClick` hook is only used internally. Currently, it is not exposed as a public API that's why it is missing in docs.

**Comment by aninde** [comment]
If this is the case then maybe we should not describe it in the RN.

 @jansiegel could you remove `onCellDblClick` from the current RN draft?

**Comment by wojciechczerniak** [comment]
> If this is the case then maybe we should not describe it in the RN.
> 
> @jansiegel could you remove `onCellDblClick` from the current RN draft?

It's still important for the end-user as this modifies how mouse events work.

**Comment by aninde** [comment]
Maybe we would add to RN a description that onCellDblClick is not in the public API, so that users do not feel frustrated that they cannot find something in Google and documentation.
